#!/usr/bin/env node
/**
 * Stage a ready-to-upload copy of the site in dist/.
 *
 * The repository root contains things a web server has no business serving —
 * the test suite, these build tools, package.json, the git metadata. This
 * copies out only what the site actually needs, adds an .htaccess tuned for
 * shared Apache hosting, and writes plain-text upload instructions alongside.
 *
 * Usage:  node tools/build-dist.mjs [--zip]
 *         --zip  also write dist/american-byways-maps.zip for hosts whose file
 *                manager can upload-and-extract an archive
 */

import { readFile, writeFile, mkdir, rm, readdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createZip } from './zip.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
const ZIP_NAME = 'american-byways-maps.zip';

/** Everything the deployed site needs, and nothing else. */
const INCLUDE_FILES = ['index.html', 'library.html', 'map.html'];

const textEncoder = new TextEncoder();
const encoderFor = (text) => textEncoder.encode(text);
const INCLUDE_DIRS = ['assets', 'data'];

/** Never ship these, even from inside an included directory. */
const EXCLUDE = new Set(['.DS_Store', 'Thumbs.db', '.gitkeep']);

const wantsZip = process.argv.includes('--zip');

async function collect(dir, base = dir, out = []) {
  for (const name of (await readdir(dir)).sort()) {
    if (EXCLUDE.has(name)) continue;
    const full = path.join(dir, name);
    const info = await stat(full);
    if (info.isDirectory()) await collect(full, base, out);
    else out.push(full);
  }
  return out;
}

const HTACCESS = `# American Byways Maps — Apache configuration
#
# Generated by tools/build-dist.mjs. Safe to upload as-is; safe to delete if
# your host is nginx or does not allow .htaccess overrides. The site works
# without it — this just fixes file types, adds compression, and sets sensible
# caching.

# ---------------------------------------------------------------------------
# File types
#
# Shared hosts often serve .gpx and .kml as text/plain or refuse them outright,
# which breaks the download links on the library page.
# ---------------------------------------------------------------------------
<IfModule mod_mime.c>
  AddType application/gpx+xml                   .gpx
  AddType application/vnd.google-earth.kml+xml  .kml
  AddType application/vnd.google-earth.kmz      .kmz
  AddType application/geo+json                  .geojson
  AddType application/json                      .json
  AddType image/svg+xml                         .svg
  AddType text/javascript                       .js
  AddType application/manifest+json             .webmanifest
</IfModule>

# ---------------------------------------------------------------------------
# HTTPS
#
# The "find my location" button does NOT work over plain http:// — browsers
# only expose the Geolocation API on secure origins. Uncomment the three lines
# below once your certificate is active.
#
# If uncommenting causes a redirect loop, your host terminates TLS at a proxy;
# use their control-panel "Force HTTPS" setting instead of these lines.
# ---------------------------------------------------------------------------
# <IfModule mod_rewrite.c>
#   RewriteEngine On
#   RewriteCond %{HTTPS} off
#   RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
# </IfModule>

# ---------------------------------------------------------------------------
# Compression — the map data and scripts are text and compress very well
# ---------------------------------------------------------------------------
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css text/javascript
  AddOutputFilterByType DEFLATE application/json application/geo+json
  AddOutputFilterByType DEFLATE application/gpx+xml image/svg+xml
  AddOutputFilterByType DEFLATE application/vnd.google-earth.kml+xml
</IfModule>

# ---------------------------------------------------------------------------
# Caching
#
# Filenames are not content-hashed, so caches are kept short deliberately:
# a stale script or catalogue is far more confusing than a re-download.
# ---------------------------------------------------------------------------
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/html                 "access plus 0 seconds"
  ExpiresByType application/json          "access plus 5 minutes"
  ExpiresByType application/geo+json      "access plus 5 minutes"
  ExpiresByType text/css                  "access plus 1 hour"
  ExpiresByType text/javascript           "access plus 1 hour"
  ExpiresByType image/svg+xml             "access plus 1 day"
  ExpiresByType application/gpx+xml       "access plus 1 day"
</IfModule>

# ---------------------------------------------------------------------------
# Do not list directory contents
# ---------------------------------------------------------------------------
<IfModule mod_autoindex.c>
  Options -Indexes
</IfModule>
`;

function deployNotes(fileCount, bytes) {
  return `American Byways Maps — upload instructions
=========================================

This folder is the complete website. There is nothing to build, install or
configure on the server: it is plain HTML, CSS and JavaScript.

  ${fileCount} files, ${(bytes / 1024).toFixed(0)} KB total


WHAT TO UPLOAD
--------------
Everything in this folder, keeping the folder structure exactly as it is:

  index.html        the map (the homepage)
  library.html      the catalogue of published maps
  map.html          redirect, so older /map.html links keep working
  .htaccess         Apache settings (see notes inside; safe to delete)
  assets/           styles, scripts, icon
  data/             the published map files and catalog.json

Do NOT rename index.html — web servers look for that name automatically.


WHERE TO PUT IT
---------------
Either location works; the site uses no absolute paths.

  Whole domain      upload into  public_html/
                    reachable at https://yourdomain.com/

  Subfolder         upload into  public_html/maps/
                    reachable at https://yourdomain.com/maps/

  Subdomain         point maps.yourdomain.com at its own folder and
                    upload there


AFTER UPLOADING
---------------
1. Open the address in a browser. You should land on the map.
2. Click "Library" in the top navigation — you should see two sample maps.
3. Click a sample map, then "Layers", and switch the basemap.

If the page loads but stays blank, or the layer list is empty, open the
browser's developer console (F12) and look at the Network tab: it is almost
always a file that did not finish uploading.


THREE THINGS WORTH KNOWING
--------------------------
Mapbox token
  It lives in assets/js/token.js, on its own so it never ends up in version
  control. Edit that one line to change or remove it, and re-upload just that
  file. Leave it empty and the site runs on the open USGS / Esri /
  OpenStreetMap basemaps with no account.

HTTPS
  The "find my location" button only works over https://. Browsers block
  location access on plain http://. See the notes inside .htaccess.

Sample data
  The two files in data/maps/ named "sample-*" are demonstration data with
  invented coordinates. They do not describe real roads. Delete them once you
  have published real maps of your own, and regenerate data/catalog.json.


PUBLISHING YOUR OWN MAPS
------------------------
1. Export a track from GaiaGPS as GPX, KML or KMZ.
2. Put the file in data/maps/.
3. Regenerate the catalogue so the library page lists it:
       npm run build
4. Re-upload data/ .

Full documentation is in README.md in the project repository.
`;
}

async function main() {
  console.log('Building the upload package…\n');

  // Always rebuild the catalogue first: shipping a stale catalog.json means the
  // library page silently disagrees with the files next to it.
  const { execPath } = process;
  const { spawnSync } = await import('node:child_process');
  const build = spawnSync(execPath, [path.join(ROOT, 'tools', 'build-catalog.mjs')], { encoding: 'utf8' });
  if (build.status !== 0) {
    console.error(build.stdout || '');
    console.error(build.stderr || '');
    console.error('Catalogue build failed — not packaging a site whose catalogue is wrong.');
    process.exit(1);
  }
  console.log(build.stdout.trim().split('\n').map((line) => `  ${line}`).join('\n'));
  console.log('');

  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  const staged = [];

  const html = [];
  for (const name of INCLUDE_FILES) {
    const source = path.join(ROOT, name);
    if (!existsSync(source)) {
      console.error(`Missing required file: ${name}`);
      process.exit(1);
    }
    html.push({ name, text: await readFile(source, 'utf8') });
  }

  const assets = [];
  for (const dir of INCLUDE_DIRS) {
    const source = path.join(ROOT, dir);
    if (!existsSync(source)) continue;
    for (const file of await collect(source)) {
      const relative = path.relative(ROOT, file).split(path.sep).join('/');
      assets.push({ name: relative, data: new Uint8Array(await readFile(file)) });
    }
  }

  // Cache-bust the scripts and stylesheets the pages load.
  //
  // Filenames here are stable — assets/js/viewer.js is always that — so a
  // browser that has one cached will keep serving it, and the deploy that
  // changed it appears to have done nothing. That failure is indistinguishable
  // from a broken deploy, and this project has spent real time on the
  // difference. Appending a hash of the file's own contents means the URL
  // changes exactly when the file does: a changed file is always fetched, an
  // unchanged one is still served from cache.
  //
  // A query string rather than a renamed file, so the paths on disk stay
  // readable and a human can still find assets/js/viewer.js on the server.
  const digest = (data) => createHash('sha256').update(data).digest('hex').slice(0, 8);
  const versions = new Map(assets.map((asset) => [asset.name, digest(asset.data)]));

  let stamped = 0;
  for (const page of html) {
    page.text = page.text.replace(/(src|href)="(assets\/[^"?#]+\.(?:js|css))"/g, (match, attr, href) => {
      const version = versions.get(href);
      if (!version) return match;
      stamped += 1;
      return `${attr}="${href}?v=${version}"`;
    });
  }

  for (const page of html) staged.push({ name: page.name, data: encoderFor(page.text) });
  staged.push(...assets);

  const bytes = staged.reduce((sum, entry) => sum + entry.data.length, 0);
  const encoder = new TextEncoder();
  console.log(`  Cache-busted ${stamped} asset reference(s) across ${html.length} page(s).`);

  // token.js is gitignored, so it may not exist. Always emit one: the pages load
  // it with a plain <script> tag, and a missing file would 404 on every visit.
  const tokenPath = path.join(ROOT, 'assets', 'js', 'token.js');
  if (existsSync(tokenPath)) {
    const token = await readFile(tokenPath, 'utf8');
    const configured = /ABMAP_MAPBOX_TOKEN\s*=\s*['"]\s*\S/.test(token);
    console.log(configured
      ? '  Mapbox token: found in assets/js/token.js — included in the package'
      : '  Mapbox token: assets/js/token.js is empty — the open basemaps will be used');
  } else {
    staged.push({ name: 'assets/js/token.js', data: encoder.encode("window.ABMAP_MAPBOX_TOKEN = '';\n") });
    console.log('  Mapbox token: none configured — shipping an empty assets/js/token.js');
  }

  staged.push({ name: '.htaccess', data: encoder.encode(HTACCESS) });
  staged.push({ name: 'UPLOAD-INSTRUCTIONS.txt', data: encoder.encode(deployNotes(staged.length + 1, bytes)) });

  for (const entry of staged) {
    const target = path.join(DIST, entry.name);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, entry.data);
  }

  const total = staged.reduce((sum, entry) => sum + entry.data.length, 0);
  console.log(`  dist/  ${staged.length} files, ${(total / 1024).toFixed(0)} KB`);
  for (const entry of staged) {
    console.log(`    ${entry.name.padEnd(38)} ${String(entry.data.length).padStart(7)} bytes`);
  }

  if (wantsZip) {
    const archive = await createZip(staged);
    await writeFile(path.join(DIST, ZIP_NAME), archive);
    console.log(`\n  dist/${ZIP_NAME}  ${(archive.length / 1024).toFixed(0)} KB compressed`);
  }

  console.log('\nUpload the contents of dist/ to your web host.');
  console.log('Instructions are repeated in dist/UPLOAD-INSTRUCTIONS.txt.');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
