/**
 * What every state's routes actually draw, on both schemas.
 *
 * Generated rather than written, and evaluated rather than described: each
 * cell is the image id the style expression produces for that input, obtained
 * by running the expression the map runs. A hand-written table of this would
 * be out of date the first time a rule moved, which is exactly the failure
 * mode the last several shield bugs had.
 *
 *   node tools/shield-matrix.mjs > docs/shield-matrix.md
 */

import {
  shieldImageExpression, statesWithShields, STATE_SHIELDS, hasShieldBlank, BANNERS,
} from '../assets/js/lib/route-shields.js';
import { evaluate } from '../test/helpers/expression.mjs';

/* The OSM/Protomaps path: the road names its own network. */
const byNetwork = (network, text = '60') => evaluate(
  shieldImageExpression('', {
    network: 'network',
    length: ['length', ['coalesce', ['get', 'shield_text'], '']],
  }),
  { properties: { network, shield_text: text } },
);

/* The Mapbox path: the road names a marker shape, and the state comes from
   whatever the viewport is over. */
const byShape = (shield, viewportState, reflen = 2) => evaluate(
  shieldImageExpression(viewportState, { length: reflen }),
  { properties: { shield, reflen } },
);

const design = (id) => String(id).replace(/^abmap-shield-/, '').replace(/-(\d)(-\w+)?$/, '$2');

const out = [];
const say = (line = '') => out.push(line);

say('# What each state draws');
say();
say('<!-- Generated by tools/shield-matrix.mjs. Do not edit by hand. -->');
say();
say('Every cell below is the design the style expression actually produces for');
say('that input, obtained by evaluating the expression rather than by describing');
say('it. Regenerate with `node tools/shield-matrix.mjs > docs/shield-matrix.md`.');
say();

say('## The rules, which do not vary by state');
say();
say('### OSM / Protomaps — the road carries `network`');
say();
say('| network | design | why |');
say('| --- | --- | --- |');
const rules = [
  ['US:I', 'the interstate is the interstate everywhere'],
  ['US:US', 'likewise the US route'],
  ['US:US:Business', 'a banner is a plate on the same shield'],
  ['US:MI', "the state's own marker"],
  ['US:MI:Business', 'banner: still the state, wearing a plate'],
  ['US:MI:Secondary', 'a third component that is not a banner'],
  ['US:MI:County', 'likewise'],
  ['US:MI:Orange', 'likewise — a county named rather than labelled'],
  ['(absent)', 'nothing says who numbered it'],
];
for (const [network, why] of rules) {
  const value = network === '(absent)' ? byNetwork('') : byNetwork(network);
  say(`| \`${network}\` | \`${design(value)}\` | ${why} |`);
}
say();
say(`Banner words, the closed set the rule is built on: ${Object.keys(BANNERS).map((b) => `\`${b}\``).join(', ')}.`);
say();

say('### Mapbox — the road carries `shield`, a marker *shape*');
say();
say('| shield | design, map over Michigan | design, map over Tennessee |');
say('| --- | --- | --- |');
for (const shield of ['us-interstate', 'us-highway', 'us-state', 'circle-white', 'diamond-white', 'something-unprobed', 'default', '(absent)']) {
  const value = shield === '(absent)' ? undefined : shield;
  say(`| \`${shield}\` | \`${design(byShape(value, 'MI'))}\` | \`${design(byShape(value, 'TN'))}\` |`);
}
say();
say('The two columns differ for every shape because the Mapbox schema never says');
say('whose road it is. The marker is the state the **viewport** is over, which is');
say('right until the screen holds two states.');
say();

say('## Per state');
say();
say('`Secondary` is the column to read. It means two different things and the');
say('word cannot tell you which: Virginia and West Virginia use it for a system');
say('of its own - the circle-signed roads a county numbers - while Michigan and');
say('Tennessee use it for their own state routes, the ones that are not trunk or');
say('primary. BUS M 60 is a Michigan state route.');
say();
say('So it is a per-state fact held in a list, and the list is short on purpose:');
say('it holds only the states somebody has actually looked at. A state showing');
say('`county` below has not been checked, not been ruled on. If its secondaries');
say('are really state routes, say so and it gets added.');
say();
say('The conservative direction is deliberate. A state route drawn in a plain');
say('circle is wrong and obviously generic; a county road wearing the state');
say('shield asserts something false about the road.');
say();
say('The last column is the Mapbox side of the same question, and it is the');
say('override list: what that state\u2019s `default` draws with the map over it.');
say('`circle` is the rule - a road nobody signed - and a state marker there');
say('means the state has been overridden, because Mapbox reports `default` for');
say('its signed state routes too and the shape arms never fire. The cost is the');
say('inverse of the paragraph above: an unsigned numbered road in an overridden');
say('state wears the state marker. Only states seen doing this are on the list.');
say();

say('| State | shape | artwork | `US:XX` | `US:XX:Secondary` | `US:XX:County` | Mapbox `default` |');
say('| --- | --- | --- | --- | --- | --- | --- |');
for (const code of statesWithShields()) {
  const shape = STATE_SHIELDS[code]?.shape || '—';
  const art = hasShieldBlank(`st-${code}`, 2) ? 'PNG' : 'drawn';
  say(`| ${code} | ${shape} | ${art} | \`${design(byNetwork(`US:${code}`))}\``
    + ` | \`${design(byNetwork(`US:${code}:Secondary`))}\``
    + ` | \`${design(byNetwork(`US:${code}:County`))}\``
    + ` | \`${design(byShape('default', code))}\` |`);
}
say();

const drawn = statesWithShields().filter((c) => !hasShieldBlank(`st-${c}`, 2));
say(`States drawn from a shape rather than artwork: ${drawn.length ? drawn.join(', ') : 'none'}.`);
say();

console.log(out.join('\n'));
